# environment changes
set-option -g default-command bash
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -ga terminal-overrides ",xterm-256color:Tc"
set-option -g history-limit 5000
set -g mouse on
set -g mode-keys vi

# copy-paste related; xclip needed for copy to sysclip in keyboard mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
# this requires xclip to be installed. sudo apt install xclip
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
bind p run "xclip -selection clipboard -o | tmux load-buffer - && tmux paste-buffer"
bind -n M-c copy-mode
bind -n M-p paste-buffer

# visual changes
set -g status-style bg=default,fg='#765FD4'
set -g mode-style "fg=default,bg=#765fd4"
set -g pane-border-lines heavy
set -g pane-border-style fg='#222222',bg=default
set -g pane-active-border-style fg='#765FD4',bg=default
set -g window-active-style bg="#000000"
set -g window-style bg=default

# navigation and panel related
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n M-f resize-pane -Z
bind -n M-n split-window -v -c "#{pane_current_path}" \; select-layout main-horizontal
bind -n M-q kill-pane\; select-layout main-horizontal

# plugins and overrides
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @scroll-without-changing-pane "on"

#TPM RUn
run '~/.tmux/plugins/tpm/tpm'
